# Generated by Django 4.1.3 on 2022-12-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
